[build]
  functions = "netlify/functions"  # Path to serverless functions
  publish = "public"  # Path to static files

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"  # Redirect API requests to the serverless function
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/uploads/:splat"  # Serve static files from 'public/uploads'
  status = 200