export const catFoodArray = [
    {
        id: 1,
        image: "/images/purefood.webp",
        title: "Wholesome Wellness",
        description: "Wholesome Wellness is a nutritious blend of real ingredients, providing your cat with a balanced and satisfying meal. Enriched with vitamins and minerals, this formula supports your cat's overall health and well-being. Suitable for cats of all ages, Wholesome Wellness offers a flavorful and wholesome meal option.",
        age: "1+ year",
        lifeStage: "Adult",
        specialty: "Mixed Flavor",
        feedingDetails: "Feed your adult cat Wholesome Wellness as part of a balanced diet to keep them healthy and happy.",
        details: "Made with real ingredients and essential nutrients."
    },
    {
        id: 2,
        image: "/images/purefood.webp",
        title: "Healthy Harvest",
        description: "Healthy Harvest offers your cat a taste of nature with a blend of real fruits and vegetables. Packed with antioxidants and fiber, this formula supports your cat's digestive health and overall well-being. Suitable for cats of all ages, Healthy Harvest provides a nutritious and flavorful meal option.",
        age: "1 year",
        lifeStage: "Adult",
        specialty: "Vegetarian Flavor",
        feedingDetails: "Feed your adult cat Healthy Harvest as part of a balanced diet to ensure they receive essential nutrients.",
        details: "Made with real fruits, vegetables, and essential nutrients."
    },
    {
        id: 3,
        image: "/images/purefood.webp",
        title: "Grain-Free Gourmet",
        description: "Grain-Free Gourmet is a premium blend of real meat and wholesome ingredients, free from grains and fillers. Enriched with vitamins and minerals, this formula supports your cat's overall health and vitality. Suitable for cats of all ages, Grain-Free Gourmet offers a delicious and nutritious meal option.",
        age: "2+ years",
        lifeStage: "Adult",
        specialty: "Grain-Free Formula",
        feedingDetails: "Feed your adult cat Grain-Free Gourmet to provide a nutritious and satisfying meal without grains.",
        details: "Made with real meat and essential nutrients, without grains."
    },
    {
        id: 4,
        image: "/images/purefood.webp",
        title: "Organic Oasis",
        description: "Organic Oasis offers your cat a taste of nature with certified organic ingredients. Enriched with vitamins and minerals, this formula supports your cat's overall health and well-being. Suitable for cats of all ages, Organic Oasis provides a wholesome and nutritious meal option.",
        age: "1+ year",
        lifeStage: "Adult",
        specialty: "Organic Flavor",
        feedingDetails: "Feed your adult cat Organic Oasis as part of a balanced diet to maintain their health and vitality.",
        details: "Made with certified organic ingredients and essential nutrients."
    },
    {
        id: 5,
        image: "/images/purefood.webp",
        title: "Premium Protein",
        description: "Premium Protein is a high-quality blend of real meat and essential nutrients, providing your cat with the protein they need for optimal health. Enriched with vitamins and minerals, this formula supports your cat's muscle development and overall well-being. Suitable for cats of all ages, Premium Protein offers a flavorful and nutritious meal option.",
        age: "6 months",
        lifeStage: "Kitten",
        specialty: "Protein-Rich Formula",
        feedingDetails: "Feed your kitten Premium Protein to support their growth and provide essential nutrients.",
        details: "Made with premium meat ingredients and essential nutrients."
    },
    {
        id: 6,
        image: "/images/purefood.webp",
        title: "Natural Nourishment",
        description: "Natural Nourishment is made with real ingredients and essential nutrients, providing your cat with a wholesome and satisfying meal option. Enriched with vitamins and minerals, this formula supports your cat's overall health and vitality. Suitable for cats of all ages, Natural Nourishment offers a balanced and nutritious meal option.",
        age: "8 months",
        lifeStage: "Kitten",
        specialty: "Natural Formula",
        feedingDetails: "Feed your kitten Natural Nourishment to support their growth and development.",
        details: "Made with real ingredients and essential nutrients."
    },
    {
        id: 7,
        image: "/images/purefood.webp",
        title: "Superfood Selection",
        description: "Superfood Selection offers your cat a variety of nutrient-rich ingredients, including real fruits and vegetables. Enriched with antioxidants and fiber, this formula supports your cat's overall health and well-being. Suitable for cats of all ages, Superfood Selection provides a flavorful and nutritious meal option.",
        age: "1 year",
        lifeStage: "Adult",
        specialty: "Superfood Blend",
        feedingDetails: "Feed your adult cat Superfood Selection as part of a balanced diet to keep them healthy and happy.",
        details: "Made with real superfood ingredients and essential nutrients."
    },
    {
        id: 8,
        image: "/images/purefood.webp",
        title: "Digestive Delight",
        description: "Digestive Delight is specially formulated to support your cat's digestive health with probiotics and fiber. Made with real ingredients and essential nutrients, this formula promotes a healthy digestive system and overall well-being. Suitable for cats of all ages, Digestive Delight offers a delicious and nutritious meal option.",
        age: "2+ years",
        lifeStage: "Adult",
        specialty: "Digestive Health Formula",
        feedingDetails: "Feed your adult cat Digestive Delight to support their digestive health and well-being.",
        details: "Made with probiotics, fiber, and essential nutrients."
    },
    {
        id: 9,
        image: "/images/purefood.webp",
        title: "Senior Support",
        description: "Senior Support is specially formulated to meet the unique nutritional needs of senior cats. Enriched with vitamins and minerals, this formula supports your cat's joint health and overall well-being. Suitable for senior cats of all ages, Senior Support provides a flavorful and nutritious meal option.",
        age: "10 years",
        lifeStage: "Senior",
        specialty: "Senior Formula",
        feedingDetails: "Feed your senior cat Senior Support as part of a balanced diet to support their health and vitality.",
        details: "Made with nutrients to support senior cats' health."
    },
    {
        id: 10,
        image: "/images/purefood.webp",
        title: "Weight Management",
        description: "Weight Management is specially formulated to help overweight cats achieve a healthy weight. Made with lean proteins and reduced fat content, this formula supports your cat's weight loss journey while providing essential nutrients. Suitable for cats of all ages, Weight Management offers a satisfying and nutritious meal option.",
        age: "5 years",
        lifeStage: "Adult",
        specialty: "Weight Control Formula",
        feedingDetails: "Feed your overweight cat Weight Management to support their weight loss journey and overall well-being.",
        details: "Made with lean proteins and reduced fat content."
    },
    {
        id: 11,
        image: "/images/purefood.webp",
        title: "Gourmet Delight",
        description: "Gourmet Delight is a luxurious blend of real meat and gourmet ingredients, offering your cat a culinary experience like no other. Enriched with vitamins and minerals, this formula supports your cat's overall health and vitality. Suitable for cats of all ages, Gourmet Delight provides a delicious and nutritious meal option.",
        age: "3+ years",
        lifeStage: "Adult",
        specialty: "Gourmet Blend",
        feedingDetails: "Feed your adult cat Gourmet Delight as a special treat to indulge their senses.",
        details: "Made with premium ingredients and essential nutrients."
    },
    {
        id: 12,
        image: "/images/purefood.webp",
        title: "Sensitive Stomach",
        description: "Sensitive Stomach is specially formulated to soothe and support your cat's digestive system. Made with easily digestible ingredients and essential nutrients, this formula promotes digestive health and overall well-being. Suitable for cats of all ages, Sensitive Stomach offers a gentle and nutritious meal option.",
        age: "4 years",
        lifeStage: "Adult",
        specialty: "Digestive Support Formula",
        feedingDetails: "Feed your cat with a sensitive stomach Sensitive Stomach to support their digestive health.",
        details: "Made with easily digestible ingredients and essential nutrients."
    },
    {
        id: 13,
        image: "/images/purefood.webp",
        title: "Hairball Control",
        description: "Hairball Control is specially formulated to reduce hairballs and support your cat's digestive health. Made with fiber and essential nutrients, this formula promotes healthy digestion and reduces hairball formation. Suitable for cats of all ages, Hairball Control offers a nutritious and satisfying meal option.",
        age: "2 years",
        lifeStage: "Adult",
        specialty: "Hairball Formula",
        feedingDetails: "Feed your cat Hairball Control to reduce hairballs and support their digestive health.",
        details: "Made with fiber and essential nutrients to reduce hairball formation."
    },
    {
        id: 14,
        image: "/images/purefood.webp",
        title: "Sensitive Skin",
        description: "Sensitive Skin is specially formulated to nourish and support your cat's skin and coat health. Enriched with omega-3 fatty acids and antioxidants, this formula promotes healthy skin and a shiny coat. Suitable for cats of all ages, Sensitive Skin offers a nutritious and delicious meal option.",
        age: "1 year",
        lifeStage: "Adult",
        specialty: "Skin & Coat Formula",
        feedingDetails: "Feed your cat Sensitive Skin to support their skin and coat health.",
        details: "Made with omega-3 fatty acids and antioxidants for healthy skin and coat."
    },
    {
        id: 15,
        image: "/images/purefood.webp",
        title: "Indoor Formula",
        description: "Indoor Formula is specially formulated to meet the unique nutritional needs of indoor cats. Enriched with fiber and essential nutrients, this formula supports your cat's digestive health and weight management. Suitable for cats of all ages, Indoor Formula offers a satisfying and nutritious meal option.",
        age: "7 years",
        lifeStage: "Adult",
        specialty: "Indoor Cat Formula",
        feedingDetails: "Feed your indoor cat Indoor Formula to support their health and well-being.",
        details: "Made with fiber and essential nutrients for indoor cats' unique needs."
    },
    {
        id: 16,
        image: "/images/purefood.webp",
        title: "Allergy Relief",
        description: "Allergy Relief is specially formulated to soothe and support your cat's allergies. Made with hypoallergenic ingredients and essential nutrients, this formula promotes allergy relief and overall well-being. Suitable for cats of all ages, Allergy Relief offers a gentle and nutritious meal option.",
        age: "9 years",
        lifeStage: "Adult",
        specialty: "Hypoallergenic Formula",
        feedingDetails: "Feed your cat Allergy Relief to provide relief from allergies and support their health.",
        details: "Made with hypoallergenic ingredients and essential nutrients."
    },
    {
        id: 17,
        image: "/images/purefood.webp",
        title: "Sensitive Teeth",
        description: "Sensitive Teeth is specially formulated to promote dental health and support your cat's oral hygiene. Made with dental-friendly ingredients and essential nutrients, this formula promotes healthy teeth and gums. Suitable for cats of all ages, Sensitive Teeth offers a nutritious and satisfying meal option.",
        age: "3 years",
        lifeStage: "Adult",
        specialty: "Dental Health Formula",
        feedingDetails: "Feed your cat Sensitive Teeth to support their dental health and oral hygiene.",
        details: "Made with dental-friendly ingredients and essential nutrients."
    },
    {
        id: 18,
        image: "/images/purefood.webp",
        title: "Immune Boost",
        description: "Immune Boost is specially formulated to strengthen and support your cat's immune system. Enriched with antioxidants and vitamins, this formula promotes immune health and overall well-being. Suitable for cats of all ages, Immune Boost offers a nutritious and delicious meal option.",
        age: "6 years",
        lifeStage: "Adult",
        specialty: "Immune Support Formula",
        feedingDetails: "Feed your cat Immune Boost to strengthen their immune system and support their health.",
        details: "Made with antioxidants and vitamins to boost immune health."
    },
    {
        id: 19,
        image: "/images/purefood.webp",
        title: "Joint Health",
        description: "Joint Health is specially formulated to support your cat's joint health and mobility. Enriched with glucosamine and chondroitin, this formula promotes healthy joints and flexibility. Suitable for cats of all ages, Joint Health offers a nutritious and satisfying meal option.",
        age: "8 years",
        lifeStage: "Adult",
        specialty: "Joint Support Formula",
        feedingDetails: "Feed your cat Joint Health to support their joint health and mobility.",
        details: "Made with glucosamine and chondroitin to support healthy joints."
    },
    {
        id: 20,
        image: "/images/purefood.webp",
        title: "Stress Relief",
        description: "Stress Relief is specially formulated to calm and soothe your cat's nerves during stressful situations. Made with calming ingredients and essential nutrients, this formula promotes relaxation and overall well-being. Suitable for cats of all ages, Stress Relief offers a gentle and nutritious meal option.",
        age: "4 years",
        lifeStage: "Adult",
        specialty: "Calming Formula",
        feedingDetails: "Feed your cat Stress Relief during stressful times to promote relaxation and calmness.",
        details: "Made with calming ingredients and essential nutrients to soothe nerves."
    },
    {
        id: 21,
        image: "/images/purefood.webp",
        title: "Sensitive Digestion",
        description: "Sensitive Digestion is specially formulated to support your cat's digestive health and reduce digestive issues. Made with easily digestible ingredients and essential nutrients, this formula promotes healthy digestion and overall well-being. Suitable for cats of all ages, Sensitive Digestion offers a gentle and nutritious meal option.",
        age: "5 years",
        lifeStage: "Adult",
        specialty: "Digestive Support Formula",
        feedingDetails: "Feed your cat Sensitive Digestion to support their digestive health and reduce digestive issues.",
        details: "Made with easily digestible ingredients and essential nutrients."
    },
    {
        id: 22,
        image: "/images/purefood.webp",
        title: "Hairball Prevention",
        description: "Hairball Prevention is specially formulated to reduce hairballs and support your cat's digestive health. Made with fiber and essential nutrients, this formula promotes healthy digestion and reduces hairball formation. Suitable for cats of all ages, Hairball Prevention offers a nutritious and satisfying meal option.",
        age: "3 years",
        lifeStage: "Adult",
        specialty: "Hairball Control Formula",
        feedingDetails: "Feed your cat Hairball Prevention to reduce hairballs and support their digestive health.",
        details: "Made with fiber and essential nutrients to reduce hairball formation."
    },
    {
        id: 23,
        image: "/images/purefood.webp",
        title: "Sensitive Skin & Coat",
        description: "Sensitive Skin & Coat is specially formulated to nourish and support your cat's skin and coat health. Enriched with omega-3 fatty acids and antioxidants, this formula promotes healthy skin and a shiny coat. Suitable for cats of all ages, Sensitive Skin & Coat offers a nutritious and delicious meal option.",
        age: "7 years",
        lifeStage: "Adult",
        specialty: "Skin & Coat Support Formula",
        feedingDetails: "Feed your cat Sensitive Skin & Coat to support their skin and coat health.",
        details: "Made with omega-3 fatty acids and antioxidants for healthy skin and coat."
    },
    {
        id: 24,
        image: "/images/purefood.webp",
        title: "Urinary Tract Health",
        description: "Urinary Tract Health is specially formulated to support your cat's urinary health and prevent urinary tract infections. Made with urinary-friendly ingredients and essential nutrients, this formula promotes a healthy urinary tract and overall well-being. Suitable for cats of all ages, Urinary Tract Health offers a nutritious and satisfying meal option.",
        age: "8 years",
        lifeStage: "Adult",
        specialty: "Urinary Health Formula",
        feedingDetails: "Feed your cat Urinary Tract Health to support their urinary health and prevent urinary tract infections.",
        details: "Made with urinary-friendly ingredients and essential nutrients."
    },
    {
        id: 25,
        image: "/images/purefood.webp",
        title: "Senior Wellness",
        description: "Senior Wellness is specially formulated to meet the unique nutritional needs of senior cats. Enriched with vitamins and minerals, this formula supports your cat's joint health and overall well-being. Suitable for senior cats of all ages, Senior Wellness provides a flavorful and nutritious meal option.",
        age: "10 years",
        lifeStage: "Senior",
        specialty: "Senior Formula",
        feedingDetails: "Feed your senior cat Senior Wellness as part of a balanced diet to support their health and vitality.",
        details: "Made with nutrients to support senior cats' health."
    }
];

export const catLitterArray = [
    {
        id: 1,
        image: "/images/purelitter.webp",
        title: "Fresh Paws",
        description: "Highly absorbent litter with odor control properties, keeping your cat's litter box fresh and clean for longer periods. This clumping formula is designed to form tight clumps for easy scooping and disposal. Made from natural clay, it is 99% dust-free, reducing tracking and mess in your home. Suitable for all ages of cats and ideal for multi-cat households.",
        age: "1+ year",
        specialty: "Clumping Formula",
        material: "Clay",
        features: "99% dust-free, low tracking formula",
        details: "Ideal for multi-cat households and offers excellent odor control and easy maintenance."
    },
    {
        id: 2,
        image: "/images/purelitter.webp",
        title: "Odor Buster",
        description: "Advanced litter formula designed to eliminate tough odors, providing a fresh and odor-free environment for your cat. Made with activated charcoal and natural odor eliminators, it traps and neutralizes unpleasant smells, leaving behind a clean scent. The silica gel crystals offer high absorbency and lightweight, non-clumping performance. Suitable for all ages of cats and perfect for households with multiple pets.",
        age: "8 months",
        specialty: "Odor Control",
        material: "Silica Gel Crystals",
        features: "High absorbency, lightweight, non-clumping",
        details: "Powerful odor neutralization with activated charcoal and natural odor eliminators."
    },
    {
        id: 3,
        image: "/images/purelitter.webp",
        title: "Natural Nest",
        description: "Environmentally friendly litter made from natural materials, providing a safe and sustainable option for your cat and the planet. Biodegradable and flushable, reducing environmental impact while offering excellent odor control and moisture absorption. The wood pellets are gentle on your cat's paws and easy to clean. Suitable for all ages of cats and perfect for eco-conscious pet owners.",
        age: "6 months",
        specialty: "Eco-Friendly",
        material: "Wood Pellets",
        features: "Biodegradable, flushable, low dust",
        details: "Eco-conscious choice with biodegradable and flushable wood pellets for excellent odor control."
    },
    {
        id: 4,
        image: "/images/purelitter.webp",
        title: "Gentle Touch",
        description: "Hypoallergenic litter formulated for cats with sensitive skin or allergies, ensuring a comfortable and irritation-free experience. Made from recycled paper, gentle on paws and skin, with a soft texture that cats love. Virtually dust-free, reducing mess and respiratory irritation in your home. Suitable for all ages of cats and ideal for households with allergy-prone pets.",
        age: "1 year",
        specialty: "Hypoallergenic",
        material: "Recycled Paper",
        features: "Soft texture, gentle on paws, virtually dust-free",
        details: "Ideal for cats with allergies, gentle on sensitive skin, and virtually dust-free for easy breathing."
    },
    {
        id: 5,
        image: "/images/purelitter.webp",
        title: "Multi-Cat Magic",
        description: "Extra-strength litter designed for multi-cat households, with enhanced clumping and odor control capabilities. Formulated to handle the heavy usage of multiple cats, it forms strong clumps that are easy to scoop and dispose of. Made from natural clay, it offers long-lasting odor control and reduced tracking. Suitable for all ages of cats and perfect for busy households with several pets.",
        age: "1+ year",
        specialty: "Multi-Cat Formula",
        material: "Clay",
        features: "Strong clumps, long-lasting odor control, low tracking",
        details: "Formulated for multi-cat households with strong clumping and long-lasting odor control."
    },
    {
        id: 6,
        image: "/images/purelitter.webp",
        title: "Fresh Paws",
        description: "Highly absorbent litter with odor control properties, keeping your cat's litter box fresh and clean for longer periods. This clumping formula is designed to form tight clumps for easy scooping and disposal. Made from natural clay, it is 99% dust-free, reducing tracking and mess in your home. Suitable for all ages of cats and ideal for multi-cat households.",
        age: "8 months",
        specialty: "Clumping Formula",
        material: "Clay",
        features: "99% dust-free, low tracking formula",
        details: "Ideal for multi-cat households and offers excellent odor control and easy maintenance."
    },
    {
        id: 7,
        image: "/images/purelitter.webp",
        title: "Odor Buster",
        description: "Advanced litter formula designed to eliminate tough odors, providing a fresh and odor-free environment for your cat. Made with activated charcoal and natural odor eliminators, it traps and neutralizes unpleasant smells, leaving behind a clean scent. The silica gel crystals offer high absorbency and lightweight, non-clumping performance. Suitable for all ages of cats and perfect for households with multiple pets.",
        age: "6 months",
        specialty: "Odor Control",
        material: "Silica Gel Crystals",
        features: "High absorbency, lightweight, non-clumping",
        details: "Powerful odor neutralization with activated charcoal and natural odor eliminators."
    },
    {
        id: 8,
        image: "/images/purelitter.webp",
        title: "Natural Nest",
        description: "Environmentally friendly litter made from natural materials, providing a safe and sustainable option for your cat and the planet. Biodegradable and flushable, reducing environmental impact while offering excellent odor control and moisture absorption. The wood pellets are gentle on your cat's paws and easy to clean. Suitable for all ages of cats and perfect for eco-conscious pet owners.",
        age: "1 year",
        specialty: "Eco-Friendly",
        material: "Wood Pellets",
        features: "Biodegradable, flushable, low dust",
        details: "Eco-conscious choice with biodegradable and flushable wood pellets for excellent odor control."
    },
    {
        id: 9,
        image: "/images/purelitter.webp",
        title: "Gentle Touch",
        description: "Hypoallergenic litter formulated for cats with sensitive skin or allergies, ensuring a comfortable and irritation-free experience. Made from recycled paper, gentle on paws and skin, with a soft texture that cats love. Virtually dust-free, reducing mess and respiratory irritation in your home. Suitable for all ages of cats and ideal for households with allergy-prone pets.",
        age: "1+ year",
        specialty: "Hypoallergenic",
        material: "Recycled Paper",
        features: "Soft texture, gentle on paws, virtually dust-free",
        details: "Ideal for cats with allergies, gentle on sensitive skin, and virtually dust-free for easy breathing."
    },
    {
        id: 10,
        image: "/images/purelitter.webp",
        title: "Multi-Cat Magic",
        description: "Extra-strength litter designed for multi-cat households, with enhanced clumping and odor control capabilities. Formulated to handle the heavy usage of multiple cats, it forms strong clumps that are easy to scoop and dispose of. Made from natural clay, it offers long-lasting odor control and reduced tracking. Suitable for all ages of cats and perfect for busy households with several pets.",
        age: "8 months",
        specialty: "Multi-Cat Formula",
        material: "Clay",
        features: "Strong clumps, long-lasting odor control, low tracking",
        details: "Formulated for multi-cat households with strong clumping and long-lasting odor control."
    },
    {
        id: 11,
        image: "/images/purelitter.webp",
        title: "Fresh Paws",
        description: "Highly absorbent litter with odor control properties, keeping your cat's litter box fresh and clean for longer periods. This clumping formula is designed to form tight clumps for easy scooping and disposal. Made from natural clay, it is 99% dust-free, reducing tracking and mess in your home. Suitable for all ages of cats and ideal for multi-cat households.",
        age: "1+ year",
        specialty: "Clumping Formula",
        material: "Clay",
        features: "99% dust-free, low tracking formula",
        details: "Ideal for multi-cat households and offers excellent odor control and easy maintenance."
    },
    {
        id: 12,
        image: "/images/purelitter.webp",
        title: "Odor Buster",
        description: "Advanced litter formula designed to eliminate tough odors, providing a fresh and odor-free environment for your cat. Made with activated charcoal and natural odor eliminators, it traps and neutralizes unpleasant smells, leaving behind a clean scent. The silica gel crystals offer high absorbency and lightweight, non-clumping performance. Suitable for all ages of cats and perfect for households with multiple pets.",
        age: "6 months",
        specialty: "Odor Control",
        material: "Silica Gel Crystals",
        features: "High absorbency, lightweight, non-clumping",
        details: "Powerful odor neutralization with activated charcoal and natural odor eliminators."
    },
    {
        id: 13,
        image: "/images/purelitter.webp",
        title: "Natural Nest",
        description: "Environmentally friendly litter made from natural materials, providing a safe and sustainable option for your cat and the planet. Biodegradable and flushable, reducing environmental impact while offering excellent odor control and moisture absorption. The wood pellets are gentle on your cat's paws and easy to clean. Suitable for all ages of cats and perfect for eco-conscious pet owners.",
        age: "8 months",
        specialty: "Eco-Friendly",
        material: "Wood Pellets",
        features: "Biodegradable, flushable, low dust",
        details: "Eco-conscious choice with biodegradable and flushable wood pellets for excellent odor control."
    },
    {
        id: 14,
        image: "/images/purelitter.webp",
        title: "Gentle Touch",
        description: "Hypoallergenic litter formulated for cats with sensitive skin or allergies, ensuring a comfortable and irritation-free experience. Made from recycled paper, gentle on paws and skin, with a soft texture that cats love. Virtually dust-free, reducing mess and respiratory irritation in your home. Suitable for all ages of cats and ideal for households with allergy-prone pets.",
        age: "1 year",
        specialty: "Hypoallergenic",
        material: "Recycled Paper",
        features: "Soft texture, gentle on paws, virtually dust-free",
        details: "Ideal for cats with allergies, gentle on sensitive skin, and virtually dust-free for easy breathing."
    },
    {
        id: 15,
        image: "/images/purelitter.webp",
        title: "Multi-Cat Magic",
        description: "Extra-strength litter designed for multi-cat households, with enhanced clumping and odor control capabilities. Formulated to handle the heavy usage of multiple cats, it forms strong clumps that are easy to scoop and dispose of. Made from natural clay, it offers long-lasting odor control and reduced tracking. Suitable for all ages of cats and perfect for busy households with several pets.",
        age: "1+ year",
        specialty: "Multi-Cat Formula",
        material: "Clay",
        features: "Strong clumps, long-lasting odor control, low tracking",
        details: "Formulated for multi-cat households with strong clumping and long-lasting odor control."
    },
    {
        id: 16,
        image: "/images/purelitter.webp",
        title: "Fresh Paws",
        description: "Highly absorbent litter with odor control properties, keeping your cat's litter box fresh and clean for longer periods. This clumping formula is designed to form tight clumps for easy scooping and disposal. Made from natural clay, it is 99% dust-free, reducing tracking and mess in your home. Suitable for all ages of cats and ideal for multi-cat households.",
        age: "6 months",
        specialty: "Clumping Formula",
        material: "Clay",
        features: "99% dust-free, low tracking formula",
        details: "Ideal for multi-cat households and offers excellent odor control and easy maintenance."
    },
    {
        id: 17,
        image: "/images/purelitter.webp",
        title: "Odor Buster",
        description: "Advanced litter formula designed to eliminate tough odors, providing a fresh and odor-free environment for your cat. Made with activated charcoal and natural odor eliminators, it traps and neutralizes unpleasant smells, leaving behind a clean scent. The silica gel crystals offer high absorbency and lightweight, non-clumping performance. Suitable for all ages of cats and perfect for households with multiple pets.",
        age: "1 year",
        specialty: "Odor Control",
        material: "Silica Gel Crystals",
        features: "High absorbency, lightweight, non-clumping",
        details: "Powerful odor neutralization with activated charcoal and natural odor eliminators."
    },
    {
        id: 18,
        image: "/images/purelitter.webp",
        title: "Natural Nest",
        description: "Environmentally friendly litter made from natural materials, providing a safe and sustainable option for your cat and the planet. Biodegradable and flushable, reducing environmental impact while offering excellent odor control and moisture absorption. The wood pellets are gentle on your cat's paws and easy to clean. Suitable for all ages of cats and perfect for eco-conscious pet owners.",
        age: "8 months",
        specialty: "Eco-Friendly",
        material: "Wood Pellets",
        features: "Biodegradable, flushable, low dust",
        details: "Eco-conscious choice with biodegradable and flushable wood pellets for excellent odor control."
    },
    {
        id: 19,
        image: "/images/purelitter.webp",
        title: "Gentle Touch",
        description: "Hypoallergenic litter formulated for cats with sensitive skin or allergies, ensuring a comfortable and irritation-free experience. Made from recycled paper, gentle on paws and skin, with a soft texture that cats love. Virtually dust-free, reducing mess and respiratory irritation in your home. Suitable for all ages of cats and ideal for households with allergy-prone pets.",
        age: "1+ year",
        specialty: "Hypoallergenic",
        material: "Recycled Paper",
        features: "Soft texture, gentle on paws, virtually dust-free",
        details: "Ideal for cats with allergies, gentle on sensitive skin, and virtually dust-free for easy breathing."
    },
    {
        id: 20,
        image: "/images/purelitter.webp",
        title: "Multi-Cat Magic",
        description: "Extra-strength litter designed for multi-cat households, with enhanced clumping and odor control capabilities. Formulated to handle the heavy usage of multiple cats, it forms strong clumps that are easy to scoop and dispose of. Made from natural clay, it offers long-lasting odor control and reduced tracking. Suitable for all ages of cats and perfect for busy households with several pets.",
        age: "6 months",
        specialty: "Multi-Cat Formula",
        material: "Clay",
        features: "Strong clumps, long-lasting odor control, low tracking",
        details: "Formulated for multi-cat households with strong clumping and long-lasting odor control."
    },
    {
        id: 21,
        image: "/images/purelitter.webp",
        title: "Fresh Paws",
        description: "Highly absorbent litter with odor control properties, keeping your cat's litter box fresh and clean for longer periods. This clumping formula is designed to form tight clumps for easy scooping and disposal. Made from natural clay, it is 99% dust-free, reducing tracking and mess in your home. Suitable for all ages of cats and ideal for multi-cat households.",
        age: "1+ year",
        specialty: "Clumping Formula",
        material: "Clay",
        features: "99% dust-free, low tracking formula",
        details: "Ideal for multi-cat households and offers excellent odor control and easy maintenance."
    },
    {
        id: 22,
        image: "/images/purelitter.webp",
        title: "Odor Buster",
        description: "Advanced litter formula designed to eliminate tough odors, providing a fresh and odor-free environment for your cat. Made with activated charcoal and natural odor eliminators, it traps and neutralizes unpleasant smells, leaving behind a clean scent. The silica gel crystals offer high absorbency and lightweight, non-clumping performance. Suitable for all ages of cats and perfect for households with multiple pets.",
        age: "1 year",
        specialty: "Odor Control",
        material: "Silica Gel Crystals",
        features: "High absorbency, lightweight, non-clumping",
        details: "Powerful odor neutralization with activated charcoal and natural odor eliminators."
    },
    {
        id: 23,
        image: "/images/purelitter.webp",
        title: "Natural Nest",
        description: "Environmentally friendly litter made from natural materials, providing a safe and sustainable option for your cat and the planet. Biodegradable and flushable, reducing environmental impact while offering excellent odor control and moisture absorption. The wood pellets are gentle on your cat's paws and easy to clean. Suitable for all ages of cats and perfect for eco-conscious pet owners.",
        age: "8 months",
        specialty: "Eco-Friendly",
        material: "Wood Pellets",
        features: "Biodegradable, flushable, low dust",
        details: "Eco-conscious choice with biodegradable and flushable wood pellets for excellent odor control."
    },
    {
        id: 24,
        image: "/images/purelitter.webp",
        title: "Gentle Touch",
        description: "Hypoallergenic litter formulated for cats with sensitive skin or allergies, ensuring a comfortable and irritation-free experience. Made from recycled paper, gentle on paws and skin, with a soft texture that cats love. Virtually dust-free, reducing mess and respiratory irritation in your home. Suitable for all ages of cats and ideal for households with allergy-prone pets.",
        age: "1+ year",
        specialty: "Hypoallergenic",
        material: "Recycled Paper",
        features: "Soft texture, gentle on paws, virtually dust-free",
        details: "Ideal for cats with allergies, gentle on sensitive skin, and virtually dust-free for easy breathing."
    },
    {
        id: 25,
        image: "/images/purelitter.webp",
        title: "Multi-Cat Magic",
        description: "Extra-strength litter designed for multi-cat households, with enhanced clumping and odor control capabilities. Formulated to handle the heavy usage of multiple cats, it forms strong clumps that are easy to scoop and dispose of. Made from natural clay, it offers long-lasting odor control and reduced tracking. Suitable for all ages of cats and perfect for busy households with several pets.",
        age: "6 months",
        specialty: "Multi-Cat Formula",
        material: "Clay",
        features: "Strong clumps, long-lasting odor control, low tracking",
        details: "Formulated for multi-cat households with strong clumping and long-lasting odor control."
    }
];


export const navigationLinks = [
    { id: 1, name: "Home", url: "/" },
    { id: 2, name: "Shop", url: "/shop" },
    { id: 3, name: "About Us", url: "/about" },
    { id: 4, name: "Blog", url: "/blog" },
    { id: 5, name: "Contact", url: "/contact" },
    { id: 6, name: "FAQ", url: "/faq" },
    { id: 7, name: "Cat Care", url: "/cat-care" },
    { id: 8, name: "Specials", url: "/specials" },
    { id: 9, name: "Reviews", url: "/reviews" },
    { id: 10, name: "Account", url: "/account" }
];